### PR TITLE
Added compatibility with Python 3 and OctoPrint 1.4.0

### PR DESCRIPTION
**Pull request by gdombiak**

### CODE REVIEW

**Comment by paukstelis** [comment]
Thanks for this. I will check it out shortly.

**Comment by gdombiak** [comment]
Been using it since then and works perfect. No issues found.

**Comment by paukstelis** [comment]
I'm getting this. Looks like an issue with populating settings...
Traceback (most recent call last):
  File "/home/paul/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint/filemanager/__init__.py", line 488, in add_file
    hook_file_object = hook(path, file_object, links=links, printer_profile=printer_profile, allow_overwrite=allow_overwrite)
  File "/home/paul/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_cancelobject/__init__.py", line 216, in modify_file
    self.reptag))
  File "/home/paul/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_cancelobject/__init__.py", line 23, in __init__
    for each in object_regex:
TypeError: 'NoneType' object is not iterable

**Comment by gdombiak** [comment]
Interesting. I tested the PR with
1. Python 2.7.13 and OctoPrint 1.3.12
1. Python 3.8.0 and OctoPrint 1.4.0rc3

What's your setup when you see that error?

**Comment by gdombiak** [comment]
When using OctoPrint 1.4.0r I found this issue https://github.com/foosel/OctoPrint/issues/3391 but the stack trace was different.

**Comment by paukstelis** [comment]
I tested with Python2.7.15 and 1.4.0rc3. I haven't installed with python3 yet.

**Comment by paukstelis** [comment]
Definitely related to loading default settings. If I modify the plugin settings and save then it works as expected.

**Comment by gdombiak** [comment]
Oh, I missed the **default** part. Yep, I'm testing with my already customized cancel plugin. Will give that a try and let you know.

**Comment by gdombiak** [comment]
Hey @paukstelis ,

So far I cannot reproduce this. This is what I did

1. Cloned fresh copy of OctoPrint and switched to staging/devel branch (1.4.0rc3)
1. Copied my modified version of the plugin under plugins folder
1.  Installed OctoPrint with Python 2.7.15
1. Deleted existing OctoPrint folder where config.yaml is stored
1. Started up OctoPrint and went through initial setup
1. Stopped OctoPrint
1. Modified config.yaml to have the virtual printer and restarted OctoPrint
1. Added a new file to OctoPrint
1. Git a breakpoint in line 23 and confirmed that *object_regex* is a collection (and not null)

Is there anything else I should do to reproduce this error? Maybe you can track it down?

Thanks,
Gaston

**Comment by gdombiak** [comment]
Here you can see the config.yaml that I ended up with. Cancel plugin it's using its own default settings.
[config.yaml.zip](https://github.com/paukstelis/Octoprint-Cancelobject/files/3965580/config.yaml.zip)

**Comment by paukstelis** [comment]
I wonder if this is related to how I installed the PR. I uninstalled under rc3 and it asked if I wanted to just remove plugin or remove plugin and associated things (I guess settings?). I did both, then installed the PR. I will see if I can duplicate.

**Comment by paukstelis** [comment]
Couldn't reproduce, and everything seemed to work after settings changes.

**Comment by gdombiak** [comment]
I wonder under which conditions object_regex is null. Do you go through a beta testing before pushing the new release out?

**Comment by paukstelis** [comment]
I have generally done installation/testing from a clean install using the virtual printer. Perhaps I should be doing more tests with migration to newer octoprint versions.

**Comment by gdombiak** [comment]
That sounds good. We both tried a fresh installed and that worked. Maybe you found something in the upgrade test case? I did not try that.

**Comment by paukstelis** [comment]
There seem to be some issue with this PR when unicode characters are present in object file names that are then included in the comments. Any suggestions on the best approach to handle this? Because it is decoded and then encoded back to ascii it is throwing the error. Is it necessary to do utf-8 decoding for python3 compatibility?

**Comment by gdombiak** [comment]
Hey Paul,

Could you tell me how to reproduce this or provide a sample gcode? I can debug it tonight and see what we can do.

Thanks,
Gaston

**Comment by gdombiak** [comment]
Python 3 does not expect or need utf-8 per se. The right answer is to decode bytes into strings using the proper character encoding that was used for generating the bytes. IOW, encoding and decoding need to use the same character encoding. A mismatch will produce incorrect results.

**Pull request merged**
